NXP-32250: admin console warning on launch
nuxeo/nuxeo-admin-console-ui pull request #11
Opened 2024-05-14 07:18 UTC by Nishant0928

2024-05-15 09:01 UTC, swarnadipa-dev requested changes

2024-05-15 09:01 UTC, swarnadipa-dev commented on src/app/shared/components/admin-warning/admin-warning.component.scss
> +  font-family: "Inter";
Remove Inter font family

2024-05-15 09:01 UTC, swarnadipa-dev commented on src/app/shared/components/admin-warning/admin-warning.component.ts
> +import { Component, Input, HostListener } from "@angular/core";
Remove Hostlistener

2024-05-15 09:01 UTC, swarnadipa-dev commented on src/app/shared/components/admin-warning/admin-warning.component.ts
> +    if (preference === "true") {
use !! operator

2024-05-15 09:32 UTC, swarnadipa-dev commented on src/app/admin-app.component.ts
> +    const preference = !!localStorage.getItem("doNotWarn");
use persistence service to get & set in localstorage

2024-05-15 09:33 UTC, swarnadipa-dev commented on src/app/shared/components/admin-warning/admin-warning.component.scss
> +  font-family: "Open Sans";
remove font-family property. It should take open sans as default font

2024-05-15 09:33 UTC, swarnadipa-dev commented on src/app/shared/components/admin-warning/admin-warning.component.ts
> +    const preference = localStorage.getItem("doNotWarn");
use persistence service

2024-05-15 09:53 UTC, swarnadipa-dev commented on src/app/admin-app.component.ts
> +    const preference = this.persistenceService.get("doNotWarn");
this variable is not required. We can directly write this as 
const doNotWarn = !!this.persistenceService.get("doNotWarn");;

2024-05-16 06:04 UTC, Nishant0928 commented on src/app/admin-app.component.ts
> +    if (preference === "true") {
done

2024-05-16 06:04 UTC, Nishant0928 commented on src/app/app.module.ts
> +import { FormsModule, ReactiveFormsModule } from "@angular/forms";
done

2024-05-16 06:04 UTC, Nishant0928 commented on src/app/shared/components/admin-warning/admin-warning.component.scss
> +  font-family: "Inter";
done

2024-05-16 06:04 UTC, Nishant0928 commented on src/app/shared/components/admin-warning/admin-warning.component.ts
> +import { Component, Input, HostListener } from "@angular/core";
done

2024-05-16 06:05 UTC, Nishant0928 commented on src/app/shared/components/admin-warning/admin-warning.component.ts
> +    if (preference === "true") {
done

2024-05-16 06:05 UTC, Nishant0928 commented on src/app/shared/components/admin-warning/admin-warning.component.ts
> +  closeDialog() {
done

2024-05-16 06:08 UTC, swarnadipa-dev approved these changes

2024-05-20 04:41 UTC, closed without merging