NAC 135: bulk action monitoring form
nuxeo/nuxeo-admin-console-ui pull request #142
Opened 2024-08-06 10:00 UTC by Nishant0928

https://jira.nuxeo.com/browse/NAC-135

2024-08-08 07:34 UTC, rakeshkumar1019 approved these changes

2024-08-08 08:13 UTC, madhurkulshrestha-hyland requested changes

2024-08-08 08:13 UTC, madhurkulshrestha-hyland commented on nuxeo-admin-console-web/angular-app/src/app/features/bulk-action-monitoring/services/bulk-action-monitoring.service.ts
> +      { urlParam: id }
There should be an object inside urlParam for generic purpose
{urlParam: {id: id}}
OR in short
{urlParam: {id}}

2024-08-08 08:13 UTC, madhurkulshrestha-hyland commented on nuxeo-admin-console-web/angular-app/src/app/shared/services/network.service.ts
> +    if (data?.["urlParam"] && url.indexOf("{id}") > -1) {
This logic should be more generic to allow any other url param besides id.
Logic -
- Check if there is a urlParam
- If yes, then extract the object from urlParam value and for each key, check if the place holder lies in the url
For eg: if urlParam has "abc" as a key, then check if apiurl/{abc}/xyz is there in the url. Similartly if urlParam has "id" as a key, then check if apiurl/{id} is there.
- If yes, then replace {id} with the actual value from the object

2024-08-08 08:13 UTC, madhurkulshrestha-hyland commented on nuxeo-admin-console-web/angular-app/src/app/features/bulk-action-monitoring/services/bulk-action-monitoring.service.ts
> +      { urlParam: id }
There could be more type of params added in the url for a generic url, and not only id

2024-08-09 06:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nuxeo/nuxeo-admin-console-ui?pullRequest=142) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/nuxeo/nuxeo-admin-console-ui?pullRequest=142) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: madhurkulshrestha-hyland<br/>:white_check_mark: Nishant0928<br/>:white_check_mark: rakeshkumar1019<br/>:x: nuxeo-webui-jx-bot<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nuxeo/nuxeo-admin-console-ui?pullRequest=142) it.</sub>

2024-08-09 07:55 UTC, closed without merging