NXP-32655: add lint & format setup
nuxeo/nuxeo-admin-console-ui pull request #34
Opened 2024-06-04 06:01 UTC by rakeshkumar1019

https://jira.nuxeo.com/browse/NXP-32655

2024-06-07 08:14 UTC, swarnadipa-dev requested changes

2024-06-07 08:14 UTC, swarnadipa-dev commented on package.json
> +    "test": "ng test",
include --code-coverage

2024-06-07 08:14 UTC, swarnadipa-dev commented on package.json
> -    "karma-coverage-istanbul-reporter": "^3.0.3",
include this

2024-06-07 08:18 UTC, rakeshkumar1019 commented on package.json
> +    "test": "ng test",
added

2024-06-07 08:18 UTC, rakeshkumar1019 commented on package.json
> -    "karma-coverage-istanbul-reporter": "^3.0.3",
included

2024-06-07 08:21 UTC, swarnadipa-dev approved these changes

2024-06-10 05:29 UTC, Nishant0928 approved these changes

2024-06-10 06:40 UTC, madhurkulshrestha-hyland approved these changes

2024-06-10 09:48 UTC, merged