SUPINT-2380: nuxeo admin console web scripts works
nuxeo/nuxeo-admin-console-ui pull request #41
Opened 2024-06-11 05:16 UTC by rakeshkumar1019

2024-06-14 10:40 UTC, madhurkulshrestha-hyland requested changes

2024-06-14 10:40 UTC, madhurkulshrestha-hyland commented on nuxeo-admin-console-package/src/main/resources/package.xml
> +  <home-page>http://localhost:8080/nuxeo/admin-console</home-page>
Either remove or edit this URL

2024-06-14 10:40 UTC, madhurkulshrestha-hyland commented on nuxeo-admin-console-web/ang-src/src/main/resources/OSGI-INF/admin-console-auth-contrib.xml
> +        <pattern>app/</pattern>
should the pattern be admin-console/ ?

2024-06-14 10:40 UTC, madhurkulshrestha-hyland commented on nuxeo-admin-console-web/ang-src/src/main/resources/OSGI-INF/deployment-fragment.xml
> +      <url-pattern>/app/*</url-pattern>
should the pattern be admin-console/ ?

2024-06-20 12:33 UTC, rakeshkumar1019 commented on nuxeo-admin-console-web/ang-src/src/main/resources/OSGI-INF/admin-console-auth-contrib.xml
> +        <pattern>app/</pattern>
its a  directory path

2024-06-20 12:34 UTC, rakeshkumar1019 commented on nuxeo-admin-console-package/src/main/resources/package.xml
> +  <home-page>http://localhost:8080/nuxeo/admin-console</home-page>
done

2024-06-20 12:34 UTC, rakeshkumar1019 commented on nuxeo-admin-console-web/ang-src/src/main/resources/OSGI-INF/deployment-fragment.xml
> +      <url-pattern>/app/*</url-pattern>
its a  directory path

2024-06-21 06:05 UTC, Nishant0928 approved these changes

2024-06-21 06:18 UTC, madhurkulshrestha-hyland submitted a review, later dismissed

2024-06-21 06:18 UTC, madhurkulshrestha-hyland commented on nuxeo-admin-console-web/src/main/resources/OSGI-INF/auth-config.xml
> +        <pattern>admin-console</pattern>
This needs to be modified

2024-06-21 06:18 UTC, madhurkulshrestha-hyland commented on pom.xml
> +  <description>admin-console</description>
Description should be a full sentence

2024-06-21 06:27 UTC, rakeshkumar1019 commented on README.md
> +Nuxeo Admin console UI is a standard base web application for Nuxeo admin useres.
done

2024-06-21 07:13 UTC, madhurkulshrestha-hyland requested changes

2024-06-21 07:13 UTC, madhurkulshrestha-hyland commented on pom.xml
> +  <artifactId>admin-console</artifactId>
May need modification

2024-06-21 07:13 UTC, madhurkulshrestha-hyland commented on nuxeo-admin-console-package/pom.xml
> +    <artifactId>admin-console</artifactId>
needs modification

2024-06-21 08:25 UTC, madhurkulshrestha-hyland approved these changes

2024-06-21 09:13 UTC, merged