NXP-32714: add signout butn
nuxeo/nuxeo-admin-console-ui pull request #65
Opened 2024-07-01 03:56 UTC by rakeshkumar1019

2024-07-03 11:28 UTC, madhurkulshrestha-hyland submitted a review, later dismissed

2024-07-03 11:28 UTC, madhurkulshrestha-hyland commented on nuxeo-admin-console-web/angular-app/src/app/auth/services/auth.service.ts
> +    const url = `${this.nuxeoJsClientService.getApiUrl()}` + "me";
included endpoint inside string interpolation

2024-07-03 11:28 UTC, madhurkulshrestha-hyland commented on nuxeo-admin-console-web/angular-app/src/app/auth/services/auth.service.ts
> +    const url = `${this.nuxeoJsClientService.getBaseUrl()}`+ "logout";
included endpoint inside string interpolation

2024-07-03 11:28 UTC, madhurkulshrestha-hyland commented on nuxeo-admin-console-web/angular-app/src/app/auth/store/effects.ts
> +            // persistenceService.set("accessToken", currentUser.token);
Remove comments

2024-07-03 11:28 UTC, madhurkulshrestha-hyland commented on nuxeo-admin-console-web/angular-app/src/app/layouts/header-bar/header-bar.component.ts
> +  selector: 'header-bar',
Double quotes should be used by default

2024-07-03 11:28 UTC, madhurkulshrestha-hyland commented on nuxeo-admin-console-web/angular-app/src/app/layouts/header-bar/header-bar.component.html
> +<!-- eslint-disable @angular-eslint/template/no-negated-async -->
Check if this is required

2024-07-03 11:28 UTC, madhurkulshrestha-hyland commented on nuxeo-admin-console-web/angular-app/src/app/layouts/header-bar/header-bar.component.ts
> +    window.location.href = _baseURL + 'login.jsp';
/login.jsp?requestedUrl=nuxeoadmin

2024-07-03 11:28 UTC, madhurkulshrestha-hyland commented on nuxeo-admin-console-web/angular-app/src/app/shared/types/user.interface.ts
> +// export interface UserInterface {
Remove constants

2024-07-04 05:55 UTC, Nishant0928 approved these changes

2024-07-04 06:01 UTC, madhurkulshrestha-hyland requested changes

2024-07-04 06:01 UTC, madhurkulshrestha-hyland commented on nuxeo-admin-console-web/angular-app/src/app/layouts/header-bar/header-bar.component.ts
> +  private redirectToHome(): void {
redirectToLogin

2024-07-04 07:22 UTC, madhurkulshrestha-hyland approved these changes

2024-07-04 07:23 UTC, swarnadipa-dev approved these changes

2024-07-04 07:52 UTC, merged