NXP-32275: admin-console-confirmation-request-dialog
nuxeo/nuxeo-admin-console-ui pull request #76
Opened 2024-07-03 11:00 UTC by Nishant0928

https://jira.nuxeo.com/browse/NXP-32275

2024-07-03 11:24 UTC, swarnadipa-dev requested changes

2024-07-03 11:24 UTC, swarnadipa-dev commented on nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.scss
> +.custom-spinner {
Are we using this class ?

2024-07-03 11:24 UTC, swarnadipa-dev commented on nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/folder-es-reindex/folder-es-reindex.component.ts
> +function secondsToHumanReadable(seconds: number): string {
This function should be moved to a pipe or a service & reused.

2024-07-03 11:24 UTC, swarnadipa-dev commented on nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.html
> +<form
please format this file

2024-07-03 11:24 UTC, swarnadipa-dev commented on nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/folder-es-reindex/folder-es-reindex.component.html
> +<form
please format this file

2024-07-03 11:24 UTC, swarnadipa-dev commented on nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/services/elastic-search-reindex.service.ts
> +    this.setSpinnerStatus(true);
this should move to the point where this action is dispatched, in the component.

2024-07-04 07:47 UTC, Nishant0928 commented on nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.scss
> +.custom-spinner {
yes we are using it

2024-07-04 08:01 UTC, swarnadipa-dev approved these changes

2024-07-04 08:09 UTC, rakeshkumar1019 requested changes

2024-07-04 08:09 UTC, rakeshkumar1019 commented on nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/folder-es-reindex/folder-es-reindex.component.html
> +        <mat-progress-spinner class="custom-spinner" mode="indeterminate">
<mat-progress-spinner `hyIcon` class="custom-spinner" mode="indeterminate">
 Ref:https://ui.hyland.io/5932dab8d/v/41976/p/0716ad-icon/t/486172

2024-07-04 08:09 UTC, rakeshkumar1019 commented on nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.html
> +        </mat-progress-spinner>
add `hyIcon` Directive here too

2024-07-04 08:12 UTC, madhurkulshrestha-hyland approved these changes

2024-07-04 08:16 UTC, rakeshkumar1019 approved these changes

2024-07-04 08:16 UTC, rakeshkumar1019 approved these changes

2024-07-04 08:17 UTC, merged