NXP-32746: Homepage, ElasticSearch Reindex fixes & additional feedback implementation
nuxeo/nuxeo-admin-console-ui pull request #92
Opened 2024-07-12 08:44 UTC by swarnadipa-dev

https://jira.nuxeo.com/browse/NXP-32746

2024-07-12 11:52 UTC, madhurkulshrestha-hyland requested changes

2024-07-12 11:52 UTC, madhurkulshrestha-hyland commented on nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/folder-es-reindex/folder-es-reindex.component.ts
> +  removeLeadingCharacters(input: string): string {
duplicate utility function used accross multiple components. Move it to a utility file in the common areas

2024-07-12 11:52 UTC, madhurkulshrestha-hyland commented on nuxeo-admin-console-web/angular-app/src/app/features/elastic-search-reindex/components/nxql-es-reindex/nxql-es-reindex.component.ts
> +      this.decodedUserInput = decodeURIComponent(query).replace(
move this to utility in common areas.

2024-07-15 05:15 UTC, Nishant0928 approved these changes

2024-07-15 05:21 UTC, madhurkulshrestha-hyland approved these changes

2024-07-15 05:25 UTC, merged